=== jinyuttt/SmartXmlSql/SmartXmlSql/SmartXmlSqlMaper.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="SqlMapper" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="Choose">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Otherwise" type="xs:string" minOccurs="0" />
        <xs:element ref="When" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="When" nillable="true">
    <xs:complexType>
      <xs:simpleContent msdata:ColumnName="When_Text" msdata:Ordinal="3">
        <xs:extension base="xs:string">
          <xs:attribute name="Prepend" type="xs:string" />
          <xs:attribute name="Dynamic" type="xs:string" />
          <xs:attribute name="IsNotEmpty" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Switch">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Default" type="xs:string" minOccurs="0" msdata:Ordinal="1" />
        <xs:element name="Case" nillable="true" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent msdata:ColumnName="Case_Text" msdata:Ordinal="2">
              <xs:extension base="xs:string">
                <xs:attribute name="Dynamic" type="xs:string" />
                <xs:attribute name="IsNotEmpty" type="xs:string" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Prepend" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="SqlMapper" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Choose" />
        <xs:element ref="When" />
        <xs:element ref="Switch" />
        <xs:element name="Statement">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Page" type="xs:string" minOccurs="0" msdata:Ordinal="1" />
              <xs:element name="Default" type="xs:string" minOccurs="0" msdata:Ordinal="2" />
              <xs:element name="Set" type="xs:string" minOccurs="0" msdata:Ordinal="3" />
              <xs:element name="Where" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Default" type="xs:string" minOccurs="0" />
                    <xs:element ref="Choose" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element ref="When" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element ref="Switch" minOccurs="0" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element ref="Choose" minOccurs="0" maxOccurs="unbounded" />
              <xs:element ref="When" minOccurs="0" maxOccurs="unbounded" />
              <xs:element ref="Switch" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="Id" type="xs:string" />
            <xs:attribute name="DB" type="xs:string" />
            <xs:attribute name="Acess" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="My">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="MYDE" type="xs:string" minOccurs="0" />
              <xs:element name="Test" type="xs:string" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jinyuttt/SmartXmlSql/SmartXmlSql/Test.xml
<?xml version="1.0" encoding="utf-8" ?>

<SqlMapper
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="SmartXmlSqlMaper.xsd">
  <Statement Id="">
 
    <Where>
      <Choose>
        <Otherwise>
          ddd
        </Otherwise>
        <When>
          sss
        </When>
      </Choose>
    </Where>
    <Switch>
    
      <Case>
        sss
      </Case>
      <Case>
        sss
      </Case>
      
    </Switch>
  </Statement>
</SqlMapper>

=== jinyuttt/SmartXmlSql/SmartXmlSqlCore/SmartXmlSqlMaper.xml
<?xml version="1.0" encoding="utf-8"?>
<SqlMapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Study/SmartXmlSql/SmartXmlSql/SmartXmlSqlMaper.xsd">
	<Statement Id="" DB="" Acess="">
   
     <Where>
			<Choose>
				<When Prepend="And" Dynamic="" IsNotEmpty="">
                       ""
        </When>
				<Otherwise>            
        </Otherwise>
			</Choose>
			<When Prepend="And" IsNotEmpty="" Dynamic="">
         ""
      </When>
			<Switch Prepend="And">
				<Case Dynamic="" IsNotEmpty="">
          ""
        </Case>
				<Default>
           ""
        </Default>
			</Switch>
			<Default>
           ""
       </Default>
		</Where>
		<Choose>
			<When Prepend="And" Dynamic="" IsNotEmpty="">
               ""
             </When>
			<Otherwise>
              ""
              </Otherwise>
		</Choose>
		<When Prepend="And" Dynamic="" IsNotEmpty="">
      ""
     </When>
		<Switch Prepend="And">
			<Case Dynamic="" IsNotEmpty="">
         ""
        </Case>
			<Default>
        ""
        </Default>
		</Switch>
		<Default>
       
        </Default>
		<Set>
    
        </Set>
	</Statement>
</SqlMapper>
